project_id = "zsquagqhilzjumfjxusk"

[functions.uploads]

[functions.draft-media]

[functions.fetch-url-metadata]
verify_jwt = false

[functions.fetch-link-preview]
verify_jwt = false

[functions.generate-icon]
verify_jwt = false

[functions.generate-category-image]
verify_jwt = false

[functions.publish-post]

[functions.create-report]

[functions.edit-post]

[functions.suggest-comment]

[functions.suggest-post]